
package com.soprabanking.amplitude.getcustomerlist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getCustomerList", targetNamespace = "http://soprabanking.com/amplitude", wsdlLocation = "file:/C:/git/mobiLoan/mobiLoan/smg-connectors/src/main/resources/wsdl/getCustomerList.wsdl")
public class GetCustomerList
    extends Service
{

    private final static URL GETCUSTOMERLIST_WSDL_LOCATION;
    private final static WebServiceException GETCUSTOMERLIST_EXCEPTION;
    private final static QName GETCUSTOMERLIST_QNAME = new QName("http://soprabanking.com/amplitude", "getCustomerList");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/mockgetCustomerListBinding?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETCUSTOMERLIST_WSDL_LOCATION = url;
        GETCUSTOMERLIST_EXCEPTION = e;
    }

    public GetCustomerList() {
        super(__getWsdlLocation(), GETCUSTOMERLIST_QNAME);
    }

    public GetCustomerList(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETCUSTOMERLIST_QNAME, features);
    }

    public GetCustomerList(URL wsdlLocation) {
        super(wsdlLocation, GETCUSTOMERLIST_QNAME);
    }

    public GetCustomerList(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETCUSTOMERLIST_QNAME, features);
    }

    public GetCustomerList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCustomerList(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetCustomerListPortType
     */
    @WebEndpoint(name = "getCustomerListPortType")
    public GetCustomerListPortType getGetCustomerListPortType() {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerListPortType"), GetCustomerListPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerListPortType
     */
    @WebEndpoint(name = "getCustomerListPortType")
    public GetCustomerListPortType getGetCustomerListPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerListPortType"), GetCustomerListPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETCUSTOMERLIST_EXCEPTION!= null) {
            throw GETCUSTOMERLIST_EXCEPTION;
        }
        return GETCUSTOMERLIST_WSDL_LOCATION;
    }

}
