
package com.soprabanking.amplitude.getcustomerfilelist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getCustomerFileList", targetNamespace = "http://soprabanking.com/amplitude", wsdlLocation = "file:/C:/git/mobiLoan/mobiLoan/smg-connectors/src/main/resources/wsdl/getCustomerFileList.wsdl")
public class GetCustomerFileList
    extends Service
{

    private final static URL GETCUSTOMERFILELIST_WSDL_LOCATION;
    private final static WebServiceException GETCUSTOMERFILELIST_EXCEPTION;
    private final static QName GETCUSTOMERFILELIST_QNAME = new QName("http://soprabanking.com/amplitude", "getCustomerFileList");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/mockgetCustomerFileListBinding?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETCUSTOMERFILELIST_WSDL_LOCATION = url;
        GETCUSTOMERFILELIST_EXCEPTION = e;
    }

    public GetCustomerFileList() {
        super(__getWsdlLocation(), GETCUSTOMERFILELIST_QNAME);
    }

    public GetCustomerFileList(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETCUSTOMERFILELIST_QNAME, features);
    }

    public GetCustomerFileList(URL wsdlLocation) {
        super(wsdlLocation, GETCUSTOMERFILELIST_QNAME);
    }

    public GetCustomerFileList(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETCUSTOMERFILELIST_QNAME, features);
    }

    public GetCustomerFileList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCustomerFileList(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetCustomerFileListPortType
     */
    @WebEndpoint(name = "getCustomerFileListPortType")
    public GetCustomerFileListPortType getGetCustomerFileListPortType() {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerFileListPortType"), GetCustomerFileListPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerFileListPortType
     */
    @WebEndpoint(name = "getCustomerFileListPortType")
    public GetCustomerFileListPortType getGetCustomerFileListPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerFileListPortType"), GetCustomerFileListPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETCUSTOMERFILELIST_EXCEPTION!= null) {
            throw GETCUSTOMERFILELIST_EXCEPTION;
        }
        return GETCUSTOMERFILELIST_WSDL_LOCATION;
    }

}
