
package com.soprabanking.amplitude.getcustomerphonenumberlist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getCustomerPhoneNumberList", targetNamespace = "http://soprabanking.com/amplitude", wsdlLocation = "file:/C:/git/mobiLoan/mobiLoan/smg-connectors/src/main/resources/wsdl/getCustomerPhoneNumberList.wsdl")
public class GetCustomerPhoneNumberList
    extends Service
{

    private final static URL GETCUSTOMERPHONENUMBERLIST_WSDL_LOCATION;
    private final static WebServiceException GETCUSTOMERPHONENUMBERLIST_EXCEPTION;
    private final static QName GETCUSTOMERPHONENUMBERLIST_QNAME = new QName("http://soprabanking.com/amplitude", "getCustomerPhoneNumberList");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/mockgetCustomerPhoneNumberListBinding?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETCUSTOMERPHONENUMBERLIST_WSDL_LOCATION = url;
        GETCUSTOMERPHONENUMBERLIST_EXCEPTION = e;
    }

    public GetCustomerPhoneNumberList() {
        super(__getWsdlLocation(), GETCUSTOMERPHONENUMBERLIST_QNAME);
    }

    public GetCustomerPhoneNumberList(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETCUSTOMERPHONENUMBERLIST_QNAME, features);
    }

    public GetCustomerPhoneNumberList(URL wsdlLocation) {
        super(wsdlLocation, GETCUSTOMERPHONENUMBERLIST_QNAME);
    }

    public GetCustomerPhoneNumberList(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETCUSTOMERPHONENUMBERLIST_QNAME, features);
    }

    public GetCustomerPhoneNumberList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCustomerPhoneNumberList(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetCustomerPhoneNumberListPortType
     */
    @WebEndpoint(name = "getCustomerPhoneNumberListPortType")
    public GetCustomerPhoneNumberListPortType getGetCustomerPhoneNumberListPortType() {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerPhoneNumberListPortType"), GetCustomerPhoneNumberListPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerPhoneNumberListPortType
     */
    @WebEndpoint(name = "getCustomerPhoneNumberListPortType")
    public GetCustomerPhoneNumberListPortType getGetCustomerPhoneNumberListPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerPhoneNumberListPortType"), GetCustomerPhoneNumberListPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETCUSTOMERPHONENUMBERLIST_EXCEPTION!= null) {
            throw GETCUSTOMERPHONENUMBERLIST_EXCEPTION;
        }
        return GETCUSTOMERPHONENUMBERLIST_WSDL_LOCATION;
    }

}
