
package com.soprabanking.amplitude.getcustomerbudgetdetail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "getCustomerBudgetDetailPortType", targetNamespace = "http://soprabanking.com/amplitude")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetCustomerBudgetDetailPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.soprabanking.amplitude.getcustomerbudgetdetail.GetStatusResponseFlow
     * @throws ErrorResponseFlow_Exception
     */
    @WebMethod(action = "getStatus")
    @WebResult(name = "getStatusResponseFlow", targetNamespace = "http://soprabanking.com/amplitude", partName = "parameters")
    public GetStatusResponseFlow getStatus(
        @WebParam(name = "getStatusRequestFlow", targetNamespace = "http://soprabanking.com/amplitude", partName = "parameters")
        GetStatusRequestFlow parameters)
        throws ErrorResponseFlow_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.soprabanking.amplitude.getcustomerbudgetdetail.GetCustomerBudgetDetailResponseFlow
     * @throws ErrorResponseFlow_Exception
     */
    @WebMethod(action = "getCustomerBudgetDetail")
    @WebResult(name = "getCustomerBudgetDetailResponseFlow", targetNamespace = "http://soprabanking.com/amplitude", partName = "parameters")
    public GetCustomerBudgetDetailResponseFlow getCustomerBudgetDetail(
        @WebParam(name = "getCustomerBudgetDetailRequestFlow", targetNamespace = "http://soprabanking.com/amplitude", partName = "parameters")
        GetCustomerBudgetDetailRequestFlow parameters)
        throws ErrorResponseFlow_Exception
    ;

}
