
package com.soprabanking.amplitude.getcustomerbudgetdetail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getCustomerBudgetDetail", targetNamespace = "http://soprabanking.com/amplitude", wsdlLocation = "file:/C:/git/mobiLoan/mobiLoan/smg-connectors/src/main/resources/wsdl/getCustomerBudgetDetail.wsdl")
public class GetCustomerBudgetDetail
    extends Service
{

    private final static URL GETCUSTOMERBUDGETDETAIL_WSDL_LOCATION;
    private final static WebServiceException GETCUSTOMERBUDGETDETAIL_EXCEPTION;
    private final static QName GETCUSTOMERBUDGETDETAIL_QNAME = new QName("http://soprabanking.com/amplitude", "getCustomerBudgetDetail");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/mockgetCustomerBudgetDetailBinding?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETCUSTOMERBUDGETDETAIL_WSDL_LOCATION = url;
        GETCUSTOMERBUDGETDETAIL_EXCEPTION = e;
    }

    public GetCustomerBudgetDetail() {
        super(__getWsdlLocation(), GETCUSTOMERBUDGETDETAIL_QNAME);
    }

    public GetCustomerBudgetDetail(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETCUSTOMERBUDGETDETAIL_QNAME, features);
    }

    public GetCustomerBudgetDetail(URL wsdlLocation) {
        super(wsdlLocation, GETCUSTOMERBUDGETDETAIL_QNAME);
    }

    public GetCustomerBudgetDetail(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETCUSTOMERBUDGETDETAIL_QNAME, features);
    }

    public GetCustomerBudgetDetail(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCustomerBudgetDetail(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetCustomerBudgetDetailPortType
     */
    @WebEndpoint(name = "getCustomerBudgetDetailPortType")
    public GetCustomerBudgetDetailPortType getGetCustomerBudgetDetailPortType() {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerBudgetDetailPortType"), GetCustomerBudgetDetailPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerBudgetDetailPortType
     */
    @WebEndpoint(name = "getCustomerBudgetDetailPortType")
    public GetCustomerBudgetDetailPortType getGetCustomerBudgetDetailPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerBudgetDetailPortType"), GetCustomerBudgetDetailPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETCUSTOMERBUDGETDETAIL_EXCEPTION!= null) {
            throw GETCUSTOMERBUDGETDETAIL_EXCEPTION;
        }
        return GETCUSTOMERBUDGETDETAIL_WSDL_LOCATION;
    }

}
