
package com.soprabanking.amplitude.getcustomercontactlist;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getCustomerContactList", targetNamespace = "http://soprabanking.com/amplitude", wsdlLocation = "file:/C:/git/mobiLoan/mobiLoan/smg-connectors/src/main/resources/wsdl/getCustomerContactList.wsdl")
public class GetCustomerContactList
    extends Service
{

    private final static URL GETCUSTOMERCONTACTLIST_WSDL_LOCATION;
    private final static WebServiceException GETCUSTOMERCONTACTLIST_EXCEPTION;
    private final static QName GETCUSTOMERCONTACTLIST_QNAME = new QName("http://soprabanking.com/amplitude", "getCustomerContactList");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/mockgetCustomerContactListBinding?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETCUSTOMERCONTACTLIST_WSDL_LOCATION = url;
        GETCUSTOMERCONTACTLIST_EXCEPTION = e;
    }

    public GetCustomerContactList() {
        super(__getWsdlLocation(), GETCUSTOMERCONTACTLIST_QNAME);
    }

    public GetCustomerContactList(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETCUSTOMERCONTACTLIST_QNAME, features);
    }

    public GetCustomerContactList(URL wsdlLocation) {
        super(wsdlLocation, GETCUSTOMERCONTACTLIST_QNAME);
    }

    public GetCustomerContactList(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETCUSTOMERCONTACTLIST_QNAME, features);
    }

    public GetCustomerContactList(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCustomerContactList(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetCustomerContactListPortType
     */
    @WebEndpoint(name = "getCustomerContactListPortType")
    public GetCustomerContactListPortType getGetCustomerContactListPortType() {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerContactListPortType"), GetCustomerContactListPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerContactListPortType
     */
    @WebEndpoint(name = "getCustomerContactListPortType")
    public GetCustomerContactListPortType getGetCustomerContactListPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "getCustomerContactListPortType"), GetCustomerContactListPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETCUSTOMERCONTACTLIST_EXCEPTION!= null) {
            throw GETCUSTOMERCONTACTLIST_EXCEPTION;
        }
        return GETCUSTOMERCONTACTLIST_WSDL_LOCATION;
    }

}
